CREATE DATABASE ETSY_DB

USE ETSY_DB

CREATE TABLE USERS (
    USER_ID INT PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(30) NOT NULL,
    FULL_NAME VARCHAR(50),
    ROLE VARCHAR(10) DEFAULT 'buyer' CHECK (ROLE IN ('buyer', 'seller', 'both'))
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(70)
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(50),
    PRICE REAL NOT NULL,
    CATEGORY_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SELLER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    TOTAL_PRICE REAL NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE SHOPPING_CART (
    CART_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE REVIEWS (
    REVIEW_ID INT PRIMARY KEY,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    RATING INT NOT NULL,
    COMMENT VARCHAR(100),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE PAYMENTS (
    PAYMENT_ID INT PRIMARY KEY,
    PAYMENT_METHOD VARCHAR(20) NOT NULL,
    AMOUNT REAL NOT NULL,
    DATE DATE,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
);

CREATE TABLE CART_ITEMS (
    CART_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (CART_ID, PRODUCT_ID),
    FOREIGN KEY (CART_ID) REFERENCES SHOPPING_CART(CART_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE ORDER_PRODUCTS (
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);