-- PROCEDURES:
-- 1. Процедура за изчисляване на броя и общата стойност на поръчките на потребител:
CREATE PROCEDURE GET_USER_SUM_ORDER
    @USER_ID INT, 
    @ORDER_COUNT INT OUTPUT, 
    @ORDER_PRICE_SUM NUMERIC(10, 2) OUTPUT
AS
BEGIN
    SELECT @ORDER_COUNT = COUNT(ORDER_ID)
    FROM ORDERS
    WHERE USER_ID = @USER_ID;

    SELECT @ORDER_PRICE_SUM = SUM(TOTAL_PRICE)
    FROM ORDERS
    WHERE USER_ID = @USER_ID;
END;

DECLARE @ORDER_COUNT INT, @ORDER_PRICE_SUM NUMERIC(10,2)
EXEC GET_USER_SUM_ORDER 1, @ORDER_COUNT OUTPUT, @ORDER_PRICE_SUM OUTPUT
PRINT 'Number of Orders: ' + CAST(@ORDER_COUNT AS VARCHAR)
PRINT 'Sum Order Price: ' + CAST(@ORDER_PRICE_SUM AS VARCHAR)


-- 2. Процедура за броя и средната оценка на ревюта на даден продукт:
CREATE PROCEDURE GET_PRODUCT_REVIEW_STATS
	@PRODUCT_ID INT,
	@REVIEW_COUNT INT OUTPUT,
	@AVERAGE_RATING NUMERIC(3,2) OUTPUT
AS
BEGIN
	SELECT @REVIEW_COUNT = COUNT(REVIEW_ID)
	FROM REVIEWS
	WHERE PRODUCT_ID = @PRODUCT_ID;

	SELECT @AVERAGE_RATING = AVG(RATING)
	FROM REVIEWS
	WHERE PRODUCT_ID = @PRODUCT_ID;
END;

DECLARE @REVIEW_COUNT INT, @AVERAGE_RATING NUMERIC(3,2)
EXEC GET_PRODUCT_REVIEW_STATS 1, @REVIEW_COUNT OUTPUT, @AVERAGE_RATING OUTPUT
PRINT 'Number of reviews: ' + CAST(@REVIEW_COUNT AS VARCHAR)
PRINT 'Average rating: '+ CAST(@AVERAGE_RATING AS VARCHAR)


-- 3. Процедура за броя, средната стойност и сумата на оценките на ревютата за даден продукт:
CREATE PROCEDURE GET_PRODUCT_REVIEW_STATS_SUM
    @PRODUCT_ID INT,
    @REVIEW_COUNT INT OUTPUT,
    @AVERAGE_RATING NUMERIC(5,2) OUTPUT,
    @SUM_RATING NUMERIC(10,2) OUTPUT
AS
BEGIN
    SELECT @REVIEW_COUNT = COUNT(REVIEW_ID)
    FROM REVIEWS
    WHERE PRODUCT_ID = @PRODUCT_ID;

    SELECT @AVERAGE_RATING = AVG(RATING)
    FROM REVIEWS
    WHERE PRODUCT_ID = @PRODUCT_ID;

    SELECT @SUM_RATING = SUM(RATING)
    FROM REVIEWS
    WHERE PRODUCT_ID = @PRODUCT_ID;
END;

DECLARE @REVIEW_COUNT INT, @AVERAGE_RATING NUMERIC(5,2), @SUM_RATING NUMERIC(10,2);
EXEC GET_PRODUCT_REVIEW_STATS_SUM 1, @REVIEW_COUNT OUTPUT, @AVERAGE_RATING OUTPUT, @SUM_RATING OUTPUT;
PRINT 'Number of reviews: ' + CAST(@REVIEW_COUNT AS VARCHAR);
PRINT 'Average rating: ' + CAST(@AVERAGE_RATING AS VARCHAR);
PRINT 'Sum rating: ' + CAST(@SUM_RATING AS VARCHAR);


-- 4. Процедура за изчисляване на броя предлагани продукти за даден продавач:
CREATE PROCEDURE GET_SELLER_PRODUCT_COUNT
	@SELLER_ID INT,
	@PRODUCT_COUNT INT OUTPUT
AS
BEGIN
	SELECT @PRODUCT_COUNT = COUNT(PRODUCT_ID)
	FROM PRODUCTS
	WHERE SELLER_ID = @SELLER_ID
END;

DECLARE @PRODUCT_COUNT INT;
EXEC GET_SELLER_PRODUCT_COUNT 1, @PRODUCT_COUNT OUTPUT;
PRINT 'Number of Products Sold by Seller: ' + CAST(@PRODUCT_COUNT AS VARCHAR);


-- 5. Процедура за изчисляване на броя продукти в дадена активна количка:
CREATE PROCEDURE GET_CART_PRODUCT_COUNT
	@USER_ID INT,
	@PRODUCT_COUNT INT OUTPUT
AS
BEGIN
	SELECT @PRODUCT_COUNT = COUNT(PRODUCT_ID)
	FROM CART_ITEMS CI JOIN SHOPPING_CART SC ON CI.CART_ID = SC.CART_ID
	WHERE SC.USER_ID = @USER_ID AND SC.STATUS = 'active';
END;

DECLARE @PRODUCT_COUNT INT
EXEC GET_CART_PRODUCT_COUNT 3, @PRODUCT_COUNT OUTPUT
PRINT 'Number of Products in Cart: ' + CAST(@PRODUCT_COUNT AS VARCHAR)